### ISSUE TITLE
new

### ISSUE THREAD

**Issue by q8263542** [xinxingli/raspberry#1]
[root@localhost ~]# ls
anaconda-ks.cfg  info.py
[root@localhost ~]# python info.py
  File "info.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

出错

**Comment by xinxingli** [comment]
用的哪一个python版本，是不是升级过？

**Comment by bingcheng1998** [comment]
出错了！
```Python
pi@pi:~/python_files $ python info.py
gpu Temp: 49.40
cpu Temp: 49.39
Traceback (most recent call last):
  File "info.py", line 51, in <module>
    main()
  File "info.py", line 21, in main
    load_5min=float(load_5min)
ValueError: invalid literal for float(): 0.76

**Comment by bingcheng1998** [comment]
找到错处了：
记得将20，21行改为以下两句即可执行
```python
	load_1min=float(load_1min[0])
	load_5min=float(load_5min[0])
```
输出结果：
```bash
pi@pi:~/python_files $ python info.py
gpu Temp: 47.20
cpu Temp: 48.31
load_1min: 1.00
load_5min: 0.00
Ramused: 265  Mb
DISK_total: 30 Gb
DISK_used: 9.2 Gb
DISK_perc: 33 %
```

**Comment by xinxingli** [comment]
确实有错误，感谢指正！
